# Weird Behavior Data Exploration

CapsLock
WPM
Error Rate
NegUD
NegUU
RSA
RSB
LSA
LSB
Copy 
Paste
Cut

# 3 sessions - same keyboard

In [9]:
import pandas as pd
from model_weird_behavior.import_data import parse_input_data

In [56]:
keys_to_get = ["Space", "Back", "LShiftKey", "Tab", "OemPeriod", "LShiftKey", "LMenu", "RShiftKey", "LControlKey", "Escape", "Delete"]

In [60]:
cmu_005 = parse_input_data("/Users/kimkraunz/Desktop/005001.txt")
def parse_counts(data, keys_to_get, user_id):
    total_n = len(data)
    data_counts = data[data['action']=="KeyDown"].groupby("key").size().reset_index()
    data_counts.columns = ['key', 'n']
    data_counts = data_counts.sort_values(by='n', ascending=False)
    data_counts['n_per_100'] = 100*data_counts['n']/total_n
    data_counts = data_counts[data_counts['key'].isin(keys_to_get)]
    # data_counts['user'] = user_id
    return data_counts

counts_005 = parse_counts(cmu_005, keys_to_get, "cmu_005")

counts_005

            key    n  n_per_100
42        Space  259   6.844609
3          Back  233   6.157505
24    LShiftKey   43   1.136364
33    OemPeriod   16   0.422833
44          Tab    5   0.132135
23        LMenu    4   0.105708
38    RShiftKey    3   0.079281
22  LControlKey    2   0.052854
13       Escape    2   0.052854
10       Delete    1   0.026427

In [54]:
cmu_005_counts = cmu_005_counts[cmu_005_counts['key'].isin(keys_to_get)]
cmu_005_counts['user'] == '005'

In [55]:
cmu_005_counts

            key    n  n_per_100
42        Space  259   6.844609
3          Back  233   6.157505
24    LShiftKey   43   1.136364
33    OemPeriod   16   0.422833
44          Tab    5   0.132135
23        LMenu    4   0.105708
38    RShiftKey    3   0.079281
22  LControlKey    2   0.052854
13       Escape    2   0.052854
10       Delete    1   0.026427